# Generated by Django 4.2.20 on 2025-03-12 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cli_nome", models.CharField(max_length=50)),
                ("cli_email", models.EmailField(max_length=50)),
                ("cli_telefone", models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_nome", models.CharField(max_length=50)),
                ("pro_descricao", models.CharField(max_length=50)),
                ("pro_preco", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ped_data", models.DateField()),
                (
                    "cli_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.cliente"
                    ),
                ),
                (
                    "pro_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.produto"
                    ),
                ),
            ],
        ),
    ]
